include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/build/**
    - example/android/**
    - example/ios/**
    - example/web/**
    - idea/**
    - .dart_tool/**
    - example/.dart_tool/**